spring:
  h2:
    console:
      enabled: true
      #path:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:dogWalking;mode=mysql
    username: sa
    driver-class-name: org.h2.Driver

jwt:
  secret: YXNkaGRha2pnaHpka2pnaHp4a2pnZmhranpkeHNoZnpqa2ZoYXNkaGRha2pnaHpka2pnaHp4a2pnZmhranpkeHNoZnpqa2Zo